# Site settings
title: Billy Ohgren
header-img: img/home-bg.jpg
email: hi@billy.nu
description: "My name is Billy, working as a freelancing app developer focused on Apple platforms such as iPhone and iPad.\'. |
A quote from my Linkedin profile: \"Three words that describe me: happy, curious, social.\" |
When I'm not working I love to travel, hack on small projects or snap some photos :)." |
baseurl: ""
url: "http://www.billy.nu"
twitter_username: ohgrenbilly
github_username:  billyohgren
email_username:  hi@billy.nu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
