# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Billy.nu
tagline:          'Billy Ohgren'
description:      'My name is Billy, working as an iOS (iPhone/iPad) developer at Bloglovin\'.
A quote from my Linkedin profile: "Three words that describe me: happy, curious, social."
When I'm not working I love to travel, hack on small projects or snap some photos :).'
url:              http://www.billy.nu
baseurl:          /

author:
  name:           'Billy Ohgren'
  url:            https://twitter.com/ohgrenbilly

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
