# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Billy.nu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Billy, working as an iOS (iPhone/iPad) developer at Bloglovin'.
  A quote from my Linkedin profile: "Three words that describe me: happy, curious, social."
  When I'm not working I love to travel, hack on small projects or snap some photos :).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.billy.nu" # the base hostname & protocol for your site
twitter_username: ohgrenbilly
github_username:  billyohgren

# Build settings
markdown: kramdown
